// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct AchievementHideCondition {
    [FieldOffset(0x00)] public BitField00Flags BitField00;
    public bool HideAchievement => BitField00.HasFlag(BitField00Flags.HideAchievement);
    public bool HideName => BitField00.HasFlag(BitField00Flags.HideName);
    public bool HideConditions => BitField00.HasFlag(BitField00Flags.HideConditions);

    [Flags]
    public enum BitField00Flags : byte {
    	HideAchievement = 1 << 0,
    	HideName = 1 << 1,
    	HideConditions = 1 << 2,
    }
}
