// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x18)]
public unsafe partial struct AdvancedVibration {
    [FieldOffset(0x00)] public int Unknown0_Offset;
    [FieldOffset(0x04)] public int Unknown1_Offset;
    [FieldOffset(0x08)] public int Unknown2_Offset;
    [FieldOffset(0x0C)] public int Unknown3;
    [FieldOffset(0x10)] public int Unknown4;
    [FieldOffset(0x14)] public int Unknown5;
}
