// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct AetherialWheel {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public int ItemUnprimed;
    /// <remarks>Item</remarks>
    [FieldOffset(0x04)] public int ItemPrimed;
    [FieldOffset(0x08)] public byte Grade;
    [FieldOffset(0x09)] public byte HoursRequired;
}
