// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x40)]
public unsafe partial struct AetherCurrentCompFlgSet {
    /// <remarks>TerritoryType</remarks>
    [FieldOffset(0x00)] public int Territory;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray15<int> _aetherCurrents;
}
