// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct AnimaWeaponFUITalkParam {
    [FieldOffset(0x00)] public int Prologue_Offset;
    [FieldOffset(0x04)] public int Epilogue_Offset;
}
