// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct AnimaWeaponIcon {
    [FieldOffset(0x00)] public int Hyperconductive;
    [FieldOffset(0x04)] public int Reborn;
    [FieldOffset(0x08)] public int Sharpened;
    [FieldOffset(0x0C)] public int Zodiac;
    [FieldOffset(0x10)] public int ZodiacLux;
}
