// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct AnimaWeapon5Param {
    [FieldOffset(0x00)] public int Name_Offset;
    /// <remarks>BaseParam</remarks>
    [FieldOffset(0x04)] public byte BaseParam;
}
