// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct AnimaWeapon5PatternGroup {
    [FieldOffset(0x00)] public int Name_Offset;
}
