// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct AOZArrangement {
    /// <remarks>AOZContentBriefingBNpc</remarks>
    [FieldOffset(0x00)] public ushort AOZContentBriefingBNpc;
    [FieldOffset(0x02)] public ushort Position;
}
