// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct Balloon {
    [FieldOffset(0x00)] public int Dialogue_Offset;
    [FieldOffset(0x04)] public bool Slowly;
}
