// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct BannerDesignPreset {
    [FieldOffset(0x00)] public int Name_Offset;
    /// <remarks>BannerBg</remarks>
    [FieldOffset(0x04)] public ushort Background;
    /// <remarks>BannerFrame</remarks>
    [FieldOffset(0x06)] public ushort Frame;
    /// <remarks>BannerDecoration</remarks>
    [FieldOffset(0x08)] public ushort Decoration;
    [FieldOffset(0x0A)] public ushort SortKey;
}
