// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct BGMFade {
    [FieldOffset(0x00)] public int SceneOut;
    [FieldOffset(0x04)] public int SceneIn;
    /// <remarks>BGMFadeType</remarks>
    [FieldOffset(0x08)] public int BGMFadeType;
}
