// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct BGMSituation {
    /// <remarks>BGM</remarks>
    [FieldOffset(0x00)] public ushort DaytimeID;
    /// <remarks>BGM</remarks>
    [FieldOffset(0x02)] public ushort NightID;
    /// <remarks>BGM</remarks>
    [FieldOffset(0x04)] public ushort BattleID;
    /// <remarks>BGM</remarks>
    [FieldOffset(0x06)] public ushort DaybreakID;
    /// <remarks>BGM</remarks>
    [FieldOffset(0x08)] public ushort TwilightID;
}
