// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct BGMSwitch {
    /// <remarks>Quest</remarks>
    [FieldOffset(0x00)] public uint Quest;
    /// <remarks>BGM, BGMSituation</remarks>
    [FieldOffset(0x04)] public ushort BGM;
    /// <remarks>BGMSystemDefine</remarks>
    [FieldOffset(0x06)] public byte BGMSystemDefine;
    [FieldOffset(0x07)] public byte Unknown0;
}
