// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct CabinetCategory {
    [FieldOffset(0x00)] public int Icon;
    /// <remarks>Addon</remarks>
    [FieldOffset(0x04)] public int Category;
    [FieldOffset(0x08)] public byte MenuOrder;
    [FieldOffset(0x09)] public byte HideOrder;
}
