// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x40)]
public unsafe partial struct Calendar {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray32<CalendarStructStruct> _calendarStruct;

    [StructLayout(LayoutKind.Explicit, Size = 0x02)]
    public partial struct CalendarStructStruct {
        [FieldOffset(0x00)] public byte Month;
        [FieldOffset(0x01)] public byte Day;
    }
}
