// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct CharaCardDesignType {
    [FieldOffset(0x00)] public bool Unknown0;
    [FieldOffset(0x01)] public bool Unknown1;
    [FieldOffset(0x02)] public bool Unknown2;
    [FieldOffset(0x03)] public BitField03Flags BitField03;
    public bool Unknown3 => BitField03.HasFlag(BitField03Flags.Unknown3);
    public bool Unknown4 => BitField03.HasFlag(BitField03Flags.Unknown4);
    public bool Unknown5 => BitField03.HasFlag(BitField03Flags.Unknown5);
    public bool Unknown6 => BitField03.HasFlag(BitField03Flags.Unknown6);
    public bool Unknown7 => BitField03.HasFlag(BitField03Flags.Unknown7);
    public bool Unknown8 => BitField03.HasFlag(BitField03Flags.Unknown8);
    public bool Unknown9 => BitField03.HasFlag(BitField03Flags.Unknown9);

    [Flags]
    public enum BitField03Flags : byte {
    	Unknown3 = 1 << 0,
    	Unknown4 = 1 << 1,
    	Unknown5 = 1 << 2,
    	Unknown6 = 1 << 3,
    	Unknown7 = 1 << 4,
    	Unknown8 = 1 << 5,
    	Unknown9 = 1 << 6,
    }
}
