// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct ChocoboRaceWeather {
    /// <remarks>Weather</remarks>
    [FieldOffset(0x00)] public int WeatherType1;
    /// <remarks>Weather</remarks>
    [FieldOffset(0x04)] public int WeatherType2;
}
