// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct ChocoboRace {
    /// <remarks>ChocoboRaceRank</remarks>
    [FieldOffset(0x00)] public byte ChocoboRaceRank;
    /// <remarks>ChocoboRaceTerritory</remarks>
    [FieldOffset(0x01)] public byte ChocoboRaceTerritory;
}
