// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct ChocoboRaceAbility {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public int Description_Offset;
    [FieldOffset(0x08)] public uint Icon;
    [FieldOffset(0x0C)] public byte Value;
    /// <remarks>ChocoboRaceAbilityType</remarks>
    [FieldOffset(0x0D)] public sbyte ChocoboRaceAbilityType;
}
