// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct ChocoboTaxiStand {
    [FieldOffset(0x00)] public int PlaceName_Offset;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray8<ushort> _targetLocations;
}
