// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct ChocoboTaxi {
    /// <remarks>ChocoboTaxiStand</remarks>
    [FieldOffset(0x00)] public uint Location;
    [FieldOffset(0x04)] public ushort TimeRequired;
    [FieldOffset(0x06)] public ushort Unknown0;
    [FieldOffset(0x08)] public byte Fare;
    [FieldOffset(0x09)] public bool Unknown1;
}
