// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct ClassJobActionSort {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public uint Unknown1;
    [FieldOffset(0x08)] public ushort Unknown2;
    [FieldOffset(0x0A)] public bool Unknown3;
}
