// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x48)]
public unsafe partial struct CompanyCraftProcess {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray12<ushort> _supplyItem;
    [FieldOffset(0x18), FixedSizeArray] internal FixedSizeArray12<ushort> _setQuantity;
    [FieldOffset(0x30), FixedSizeArray] internal FixedSizeArray12<ushort> _setsRequired;
}
