// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct Completion {
    [FieldOffset(0x00)] public int Text_Offset;
    [FieldOffset(0x04)] public int GroupTitle_Offset;
    [FieldOffset(0x08)] public int LookupTable_Offset;
    [FieldOffset(0x0C)] public ushort Group;
    [FieldOffset(0x0E)] public ushort Key;
}
