// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct CompanyCraftSupplyItem {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public uint Item;
}
