// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x18)]
public unsafe partial struct CompanyCraftDraftCategory {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray10<ushort> _companyCraftType;
}
