// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct CompanyCraftPart {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray3<ushort> _companyCraftProcess;
    [FieldOffset(0x06)] public ushort Unknown0;
    [FieldOffset(0x08)] public byte Unknown1;
    /// <remarks>CompanyCraftType</remarks>
    [FieldOffset(0x09)] public byte CompanyCraftType;
}
