// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct Condition {
    /// <remarks>LogMessage</remarks>
    [FieldOffset(0x00)] public uint LogMessage;
    [FieldOffset(0x04)] public byte Unknown0;
    [FieldOffset(0x05)] public byte Unknown1;
    [FieldOffset(0x06)] public bool Unknown2;
}
