// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct ContentExAction {
    /// <remarks>Action</remarks>
    [FieldOffset(0x00)] public uint Name;
    [FieldOffset(0x04)] public uint Unknown0;
    [FieldOffset(0x08)] public byte Charges;
    [FieldOffset(0x09)] public byte Unknown1;
}
