// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct ContentTalk {
    [FieldOffset(0x00)] public int Text_Offset;
    /// <remarks>ContentTalkParam</remarks>
    [FieldOffset(0x04)] public byte ContentTalkParam;
}
