// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct ContentType {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public uint Icon;
    [FieldOffset(0x08)] public uint IconDutyFinder;
    [FieldOffset(0x0C)] public byte Unknown1;
    [FieldOffset(0x0D)] public byte Unknown2;
}
