// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct ContentTalkParam {
    /// <remarks>ActionTimeline</remarks>
    [FieldOffset(0x00)] public uint TestAction;
    [FieldOffset(0x04)] public byte Unknown0;
    [FieldOffset(0x05)] public byte Unknown1;
    [FieldOffset(0x06)] public sbyte Unknown2;
    [FieldOffset(0x07)] public sbyte Unknown3;
    [FieldOffset(0x08)] public bool Param;
}
