// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct ContentRandomSelect {
    /// <remarks>ContentFinderCondition</remarks>
    [FieldOffset(0x00)] public ushort Name;
}
