// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x24)]
public unsafe partial struct ContentNpcTalk {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray8<uint> _contentTalk;
    [FieldOffset(0x20)] public int Type;
}
