// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct CutScreenImage {
    [FieldOffset(0x00)] public int Image;
    [FieldOffset(0x04)] public short Type;
    [FieldOffset(0x06)] public short Unknown0;
}
