// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct DeepDungeonMap5X {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray5<ushort> _deepDungeonRoom;
}
