// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct DeepDungeonRoom {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray5<uint> _level;
}
