// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct DeliveryQuest {
    /// <remarks>Quest</remarks>
    [FieldOffset(0x00)] public int Quest;
}
