// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct DescriptionSection {
    /// <remarks>DescriptionString</remarks>
    [FieldOffset(0x00)] public ushort String;
    /// <remarks>DescriptionPage</remarks>
    [FieldOffset(0x02)] public ushort Page;
}
