// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x50)]
public unsafe partial struct DescriptionPage {
    /// <remarks>Quest</remarks>
    [FieldOffset(0x00)] public uint Quest;
    [FieldOffset(0x04)] public uint Unknown2;
    [FieldOffset(0x08), FixedSizeArray] internal FixedSizeArray11<uint> _image;
    [FieldOffset(0x34), FixedSizeArray] internal FixedSizeArray11<ushort> _text;
    [FieldOffset(0x4A)] public ushort Unknown0;
    [FieldOffset(0x4C)] public byte Unknown1;
}
