// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x38)]
public unsafe partial struct DpsChallengeOfficer {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray25<ushort> _challengeName;
    /// <remarks>Quest</remarks>
    [FieldOffset(0x34)] public uint UnlockQuest;
}
