// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct EmoteMode {
    /// <remarks>Emote</remarks>
    [FieldOffset(0x00)] public ushort StartEmote;
    /// <remarks>Emote</remarks>
    [FieldOffset(0x02)] public ushort EndEmote;
    [FieldOffset(0x04)] public byte ConditionMode;
    [FieldOffset(0x05)] public BitField05Flags BitField05;
    public bool Move => BitField05.HasFlag(BitField05Flags.Move);
    public bool Camera => BitField05.HasFlag(BitField05Flags.Camera);
    public bool EndOnRotate => BitField05.HasFlag(BitField05Flags.EndOnRotate);
    public bool EndOnEmote => BitField05.HasFlag(BitField05Flags.EndOnEmote);
    public bool Unknown0 => BitField05.HasFlag(BitField05Flags.Unknown0);

    [Flags]
    public enum BitField05Flags : byte {
    	Move = 1 << 0,
    	Camera = 1 << 1,
    	EndOnRotate = 1 << 2,
    	EndOnEmote = 1 << 3,
    	Unknown0 = 1 << 4,
    }
}
