// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct EurekaMagiaAction {
    /// <remarks>Action</remarks>
    [FieldOffset(0x00)] public uint Action;
    [FieldOffset(0x04)] public byte MaxUses;
}
