// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct EurekaMagiciteItemType {
    [FieldOffset(0x00)] public int Type_Offset;
}
