// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct EurekaMagiciteItem {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public uint Item;
    /// <remarks>EurekaMagiciteItemType</remarks>
    [FieldOffset(0x04)] public byte EurekaMagiciteItemType;
    /// <remarks>ClassJobCategory</remarks>
    [FieldOffset(0x05)] public byte ClassJobCategory;
}
