// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct EurekaLogosMixerProbability {
    [FieldOffset(0x00)] public byte ProbabilityPercent;
}
