// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0xCC)]
public unsafe partial struct EventCustomIconType {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray10<IconsStruct> _icons;
    [FieldOffset(0xC8)] public byte Unknown0;

    [StructLayout(LayoutKind.Explicit, Size = 0x14)]
    public partial struct IconsStruct {
        [FieldOffset(0x00)] public uint AnnounceQuest;
        [FieldOffset(0x04)] public uint AnnounceQuestLocked;
        [FieldOffset(0x08)] public uint MapAnnounceQuest1;
        [FieldOffset(0x0C)] public uint MapAnnounceQuestLocked;
        [FieldOffset(0x10)] public uint MapAnnounceQuest2;
    }
}
