// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct EventVfx {
    [FieldOffset(0x00)] public int Unknown0_Offset;
    [FieldOffset(0x04)] public int Unknown1_Offset;
    [FieldOffset(0x08)] public byte Unknown2;
    [FieldOffset(0x09)] public byte Unknown3;
    [FieldOffset(0x0A)] public byte Unknown4;
    [FieldOffset(0x0B)] public byte Unknown5;
}
