// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct FateMode {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public uint MotivationIcon;
    [FieldOffset(0x08)] public uint MotivationMapMarker;
    [FieldOffset(0x0C)] public uint ObjectiveIcon;
    [FieldOffset(0x10)] public uint ObjectiveMapMarker;
}
