// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct FateProgressUI {
    /// <remarks>TerritoryType</remarks>
    [FieldOffset(0x00)] public int Location;
    [FieldOffset(0x04)] public byte ReqFatesToRank2;
    [FieldOffset(0x05)] public byte ReqFatesToRank3;
    [FieldOffset(0x06)] public byte ReqFatesToRank4;
    [FieldOffset(0x07)] public byte DisplayOrder;
    [FieldOffset(0x08)] public sbyte Unknown0;
}
