// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct FateTokenType {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public uint Currency;
}
