// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct FCAuthority {
    [FieldOffset(0x00)] public int Name_Offset;
    /// <remarks>FCAuthorityCategory</remarks>
    [FieldOffset(0x04)] public int FCAuthorityCategory;
    [FieldOffset(0x08)] public byte Unknown0;
}
