// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct FCRank {
    [FieldOffset(0x00)] public uint NextPoint;
    [FieldOffset(0x04)] public uint CurrentPoint;
    [FieldOffset(0x08)] public ushort Rights;
    [FieldOffset(0x0A)] public ushort Unknown0;
    [FieldOffset(0x0C)] public ushort Unknown1;
    [FieldOffset(0x0E)] public byte FCActionActiveNum;
    [FieldOffset(0x0F)] public byte FCActionStockNum;
    [FieldOffset(0x10)] public byte FCChestCompartments;
}
