// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct FieldMarker {
    [FieldOffset(0x00)] public int Name_Offset;
    /// <remarks>VFX</remarks>
    [FieldOffset(0x04)] public int VFX;
    [FieldOffset(0x08)] public ushort UiIcon;
    [FieldOffset(0x0A)] public ushort MapIcon;
}
