// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct FurnitureCatalogItemList {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public int Item;
    /// <remarks>FurnitureCatalogCategory</remarks>
    [FieldOffset(0x04)] public ushort Category;
    [FieldOffset(0x06)] public ushort Patch;
}
