// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct GameRewardObtainType {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public uint Unknown1;
}
