// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct GardeningSeed {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public uint Item;
    [FieldOffset(0x04)] public uint Icon;
    [FieldOffset(0x08)] public ushort ModelID;
    [FieldOffset(0x0A)] public byte Unknown0;
    [FieldOffset(0x0B)] public BitField0BFlags BitField0B;
    public bool SE => BitField0B.HasFlag(BitField0BFlags.SE);
    public bool Unknown1 => BitField0B.HasFlag(BitField0BFlags.Unknown1);

    [Flags]
    public enum BitField0BFlags : byte {
    	SE = 1 << 0,
    	Unknown1 = 1 << 1,
    }
}
