// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x28)]
public unsafe partial struct GatheringPointBase {
    /// <remarks>GatheringType</remarks>
    [FieldOffset(0x00)] public int GatheringType;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray8<int> _item;
    [FieldOffset(0x24)] public byte GatheringLevel;
}
