// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct GatheringLeveRule {
    [FieldOffset(0x00)] public int Rule_Offset;
}
