// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct GatheringPoint {
    /// <remarks>GatheringPointBase</remarks>
    [FieldOffset(0x00)] public int GatheringPointBase;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray2<ushort> _gatheringPointBonus;
    /// <remarks>TerritoryType</remarks>
    [FieldOffset(0x08)] public ushort TerritoryType;
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x0A)] public ushort PlaceName;
    /// <remarks>GatheringSubCategory</remarks>
    [FieldOffset(0x0C)] public ushort GatheringSubCategory;
    [FieldOffset(0x0E)] public byte Type;
    [FieldOffset(0x0F)] public byte Unknown0;
    [FieldOffset(0x10)] public byte Count;
}
