// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct GatheringSubCategory {
    [FieldOffset(0x00)] public int FolkloreBook_Offset;
    /// <remarks>Quest</remarks>
    [FieldOffset(0x04)] public uint Quest;
    /// <remarks>Item</remarks>
    [FieldOffset(0x08)] public int Item;
    [FieldOffset(0x0C)] public ushort Division;
    /// <remarks>GatheringType</remarks>
    [FieldOffset(0x0E)] public byte GatheringType;
    /// <remarks>ClassJob</remarks>
    [FieldOffset(0x0F)] public byte ClassJob;
    [FieldOffset(0x10)] public byte Unknown0;
}
