// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct GathererReductionReward {
    [FieldOffset(0x00)] public ushort Unknown0;
    [FieldOffset(0x02)] public bool Unknown1;
}
