// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct GatheringItemLevelConvertTable {
    [FieldOffset(0x00)] public byte GatheringItemLevel;
    [FieldOffset(0x01)] public byte Stars;
}
