// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct GatheringRarePopTimeTable {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray3<ushort> _startTime;
    [FieldOffset(0x06), FixedSizeArray] internal FixedSizeArray3<ushort> _duration;
}
