// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct GcArmyTraining {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public int Description_Offset;
    [FieldOffset(0x08)] public uint Experience;
    [FieldOffset(0x0C)] public sbyte PhysicalBonus;
    [FieldOffset(0x0D)] public sbyte MentalBonus;
    [FieldOffset(0x0E)] public sbyte TacticalBonus;
}
