// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct GCScripShopCategory {
    /// <remarks>GrandCompany</remarks>
    [FieldOffset(0x00)] public sbyte GrandCompany;
    [FieldOffset(0x01)] public sbyte Tier;
    [FieldOffset(0x02)] public sbyte SubCategory;
}
