// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct GCScripShopItem {
    [FieldOffset(0x00)] public uint CostGCSeals;
    /// <remarks>Item</remarks>
    [FieldOffset(0x04)] public int Item;
    /// <remarks>GrandCompanyRank</remarks>
    [FieldOffset(0x08)] public int RequiredGrandCompanyRank;
    [FieldOffset(0x0C)] public byte SortKey;
}
