// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct GCShop {
    /// <remarks>GrandCompany</remarks>
    [FieldOffset(0x00)] public sbyte GrandCompany;
}
