// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct GFateClimbing2Content {
    /// <remarks>PublicContentTextData</remarks>
    [FieldOffset(0x00)] public uint PublicContentTextData;
}
