// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct GroupPoseStampFontColor {
    [FieldOffset(0x00)] public int Unknown0_Offset;
    [FieldOffset(0x04)] public int Unknown1;
    [FieldOffset(0x08)] public int Unknown2;
    [FieldOffset(0x0C)] public byte Unknown3;
}
