// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct GroupPoseCharacterShowPreset {
    [FieldOffset(0x00)] public BitField00Flags BitField00;
    public bool Unknown0 => BitField00.HasFlag(BitField00Flags.Unknown0);
    public bool Unknown1 => BitField00.HasFlag(BitField00Flags.Unknown1);
    public bool Unknown2 => BitField00.HasFlag(BitField00Flags.Unknown2);
    public bool Unknown3 => BitField00.HasFlag(BitField00Flags.Unknown3);
    public bool Unknown4 => BitField00.HasFlag(BitField00Flags.Unknown4);
    public bool Unknown5 => BitField00.HasFlag(BitField00Flags.Unknown5);
    public bool Unknown6 => BitField00.HasFlag(BitField00Flags.Unknown6);
    public bool Unknown7 => BitField00.HasFlag(BitField00Flags.Unknown7);
    [FieldOffset(0x01)] public BitField01Flags BitField01;
    public bool Unknown8 => BitField01.HasFlag(BitField01Flags.Unknown8);
    public bool Unknown9 => BitField01.HasFlag(BitField01Flags.Unknown9);
    public bool Unknown10 => BitField01.HasFlag(BitField01Flags.Unknown10);
    public bool Unknown11 => BitField01.HasFlag(BitField01Flags.Unknown11);
    public bool Unknown12 => BitField01.HasFlag(BitField01Flags.Unknown12);
    public bool Unknown13 => BitField01.HasFlag(BitField01Flags.Unknown13);

    [Flags]
    public enum BitField00Flags : byte {
    	Unknown0 = 1 << 0,
    	Unknown1 = 1 << 1,
    	Unknown2 = 1 << 2,
    	Unknown3 = 1 << 3,
    	Unknown4 = 1 << 4,
    	Unknown5 = 1 << 5,
    	Unknown6 = 1 << 6,
    	Unknown7 = 1 << 7,
    }
    [Flags]
    public enum BitField01Flags : byte {
    	Unknown8 = 1 << 0,
    	Unknown9 = 1 << 1,
    	Unknown10 = 1 << 2,
    	Unknown11 = 1 << 3,
    	Unknown12 = 1 << 4,
    	Unknown13 = 1 << 5,
    }
}
