// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct GuidePage {
    [FieldOffset(0x00)] public uint Output;
    [FieldOffset(0x04)] public byte Key;
    [FieldOffset(0x05)] public bool Unknown_70;
}
