// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x18)]
public unsafe partial struct GuildOrderOfficer {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public uint Unknown1;
    [FieldOffset(0x08)] public uint Unknown2;
    [FieldOffset(0x0C)] public uint Unknown3;
    [FieldOffset(0x10)] public uint Unknown4;
    [FieldOffset(0x14)] public uint Unknown5;
}
