// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct HousingPileLimit {
    [FieldOffset(0x00)] public ushort Unknown0;
    [FieldOffset(0x02)] public ushort Unknown1;
    [FieldOffset(0x04)] public ushort Unknown2;
    [FieldOffset(0x06)] public bool Unknown3;
    [FieldOffset(0x07)] public bool Unknown4;
    [FieldOffset(0x08)] public bool Unknown5;
    [FieldOffset(0x09)] public bool Unknown6;
    [FieldOffset(0x0A)] public bool Unknown7;
}
