// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct HousingAethernet {
    /// <remarks>Level</remarks>
    [FieldOffset(0x00)] public uint Level;
    /// <remarks>TerritoryType</remarks>
    [FieldOffset(0x04)] public ushort TerritoryType;
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x06)] public ushort PlaceName;
    [FieldOffset(0x08)] public byte Order;
}
