// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct HousingMerchantPose {
    [FieldOffset(0x00)] public int Pose_Offset;
    /// <remarks>ActionTimeline</remarks>
    [FieldOffset(0x04)] public ushort ActionTimeline;
}
