// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct HousingExterior {
    [FieldOffset(0x00)] public int Model_Offset;
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x04)] public ushort PlaceName;
    [FieldOffset(0x06)] public byte Unknown0;
    [FieldOffset(0x07)] public byte Unknown1;
    [FieldOffset(0x08)] public byte HousingSize;
}
