// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x4B8)]
public unsafe partial struct HousingLandSet {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray60<LandSetStruct> _landSet;
    [FieldOffset(0x4B0)] public uint UnknownRange1;
    [FieldOffset(0x4B4)] public uint UnknownRange2;

    [StructLayout(LayoutKind.Explicit, Size = 0x14)]
    public partial struct LandSetStruct {
        [FieldOffset(0x00)] public uint UnknownRange1;
        [FieldOffset(0x04)] public uint PlacardId;
        [FieldOffset(0x08)] public uint UnknownRange2;
        [FieldOffset(0x0C)] public uint InitialPrice;
        [FieldOffset(0x10)] public byte PlotSize;
    }
}
