// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct HowToPage {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray3<int> _text;
    [FieldOffset(0x0C)] public int Image;
    [FieldOffset(0x10)] public byte Type;
    [FieldOffset(0x11)] public byte IconType;
    [FieldOffset(0x12)] public byte TextType;
}
