// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct HWDAnnounce {
    [FieldOffset(0x00)] public int Name_Offset;
    /// <remarks>ENpcResident</remarks>
    [FieldOffset(0x04)] public uint ENPC;
    [FieldOffset(0x08)] public byte Unknown0;
    [FieldOffset(0x09)] public byte Unknown1;
}
