// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct HWDDevLively {
    /// <remarks>ENpcBase</remarks>
    [FieldOffset(0x00)] public uint ENPC;
    [FieldOffset(0x04)] public ushort Unknown0;
    [FieldOffset(0x06)] public byte Unknown1;
}
