// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct HWDGathererInspectionReward {
    [FieldOffset(0x00)] public ushort Scrips;
    [FieldOffset(0x02)] public ushort Points;
}
