// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x28)]
public unsafe partial struct IKDRoute {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray3<uint> _spot;
    [FieldOffset(0x10)] public uint Image;
    [FieldOffset(0x14)] public uint Unknown0;
    [FieldOffset(0x18)] public uint Unknown1;
    /// <remarks>ContentFinderCondition</remarks>
    [FieldOffset(0x1C)] public uint Instance;
    [FieldOffset(0x20)] public uint Unknown2;
    [FieldOffset(0x24), FixedSizeArray] internal FixedSizeArray3<byte> _time;
}
