// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct IKDSpot {
    /// <remarks>FishingSpot</remarks>
    [FieldOffset(0x00)] public uint SpotMain;
    /// <remarks>FishingSpot</remarks>
    [FieldOffset(0x04)] public uint SpotSub;
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x08)] public uint PlaceName;
}
