// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct InclusionShopCategory {
    [FieldOffset(0x00)] public int Name_Offset;
    /// <remarks>InclusionShopSeries</remarks>
    [FieldOffset(0x04)] public ushort InclusionShopSeries;
    /// <remarks>ClassJobCategory</remarks>
    [FieldOffset(0x06)] public byte ClassJobCategory;
}
