// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct InstanceContentBuff {
    [FieldOffset(0x00)] public ushort EchoStart;
    [FieldOffset(0x02)] public ushort EchoDeath;
}
