// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct ItemOnceHqMasterpiece {
    [FieldOffset(0x00)] public BitField00Flags BitField00;
    public bool Unknown0 => BitField00.HasFlag(BitField00Flags.Unknown0);
    public bool Unknown1 => BitField00.HasFlag(BitField00Flags.Unknown1);

    [Flags]
    public enum BitField00Flags : byte {
    	Unknown0 = 1 << 0,
    	Unknown1 = 1 << 1,
    }
}
