// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct ItemUICategory {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public int Icon;
    [FieldOffset(0x08)] public byte OrderMinor;
    [FieldOffset(0x09)] public byte OrderMajor;
}
