// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct JournalGenre {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public int Icon;
    /// <remarks>JournalCategory</remarks>
    [FieldOffset(0x08)] public byte JournalCategory;
    [FieldOffset(0x09)] public bool Unknown0;
}
