// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct Knockback {
    [FieldOffset(0x00)] public byte Distance;
    [FieldOffset(0x01)] public byte Speed;
    [FieldOffset(0x02)] public byte NearDistance;
    [FieldOffset(0x03)] public byte Direction;
    [FieldOffset(0x04)] public byte DirectionArg;
    [FieldOffset(0x05)] public BitField05Flags BitField05;
    public bool Motion => BitField05.HasFlag(BitField05Flags.Motion);
    public bool CancelMove => BitField05.HasFlag(BitField05Flags.CancelMove);

    [Flags]
    public enum BitField05Flags : byte {
    	Motion = 1 << 0,
    	CancelMove = 1 << 1,
    }
}
