// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct LoadingTips {
    [FieldOffset(0x00)] public bool Unknown0;
    [FieldOffset(0x04)] public int Unknown1;
    [FieldOffset(0x08)] public byte Unknown2;
}
