// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct LogFilter {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public int Example_Offset;
    [FieldOffset(0x08)] public ushort Caster;
    [FieldOffset(0x0A)] public ushort Target;
    [FieldOffset(0x0C)] public byte LogKind;
    [FieldOffset(0x0D)] public byte Category;
    [FieldOffset(0x0E)] public byte DisplayOrder;
    [FieldOffset(0x0F)] public byte Preset;
}
