// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct LogKind {
    [FieldOffset(0x00)] public int Format_Offset;
    [FieldOffset(0x04)] public byte Unknown0;
    [FieldOffset(0x05)] public bool Unknown1;
}
