// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct MacroIcon {
    [FieldOffset(0x00)] public int Icon;
    [FieldOffset(0x04)] public ushort Unknown0;
}
