// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct MapSymbol {
    [FieldOffset(0x00)] public int Icon;
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x04)] public int PlaceName;
    [FieldOffset(0x08)] public bool DisplayNavi;
}
