// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x64)]
public unsafe partial struct Materia {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray16<int> _item;
    [FieldOffset(0x40), FixedSizeArray] internal FixedSizeArray16<short> _value;
    /// <remarks>BaseParam</remarks>
    [FieldOffset(0x60)] public byte BaseParam;
}
