// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct MinionRules {
    [FieldOffset(0x00)] public int Rule_Offset;
    [FieldOffset(0x04)] public int Description_Offset;
}
