// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct MJIDisposalShopItem {
    [FieldOffset(0x00)] public ushort Unknown0;
    [FieldOffset(0x02)] public byte Unknown1;
    [FieldOffset(0x03)] public byte Unknown2;
    /// <remarks>MJIDisposalShopUICategory</remarks>
    [FieldOffset(0x04)] public byte Category;
    [FieldOffset(0x05)] public byte Unknown3;
}
