// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct MJIGatheringObject {
    [FieldOffset(0x00)] public uint MapIcon;
    [FieldOffset(0x04)] public uint Unknown0;
    /// <remarks>EObjName</remarks>
    [FieldOffset(0x08)] public uint Name;
    /// <remarks>ExportedSG</remarks>
    [FieldOffset(0x0C)] public ushort SGB;
    [FieldOffset(0x0E)] public ushort Unknown1;
}
