// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct MJIGathering {
    /// <remarks>MJIGatheringObject</remarks>
    [FieldOffset(0x00)] public byte GatheringObject;
}
