// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct MJINekomimiRequest {
    [FieldOffset(0x00)] public byte Unknown0;
    [FieldOffset(0x01)] public byte Unknown1;
    [FieldOffset(0x02)] public byte Unknown2;
    [FieldOffset(0x03)] public byte Unknown3;
}
