// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct MJIRank {
    [FieldOffset(0x00)] public uint ExpToNext;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray3<uint> _logMessage;
    [FieldOffset(0x10)] public byte Unknown0;
}
