// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct MobHuntReward {
    [FieldOffset(0x00)] public uint ExpReward;
    [FieldOffset(0x04)] public ushort GilReward;
    [FieldOffset(0x06)] public ushort CurrencyReward;
    /// <remarks>ExVersion</remarks>
    [FieldOffset(0x08)] public byte Expansion;
}
