// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct MobHuntOrder {
    /// <remarks>MobHuntTarget</remarks>
    [FieldOffset(0x00)] public ushort Target;
    [FieldOffset(0x02)] public byte NeededKills;
    [FieldOffset(0x03)] public byte Type;
    [FieldOffset(0x04)] public byte Rank;
    /// <remarks>MobHuntReward</remarks>
    [FieldOffset(0x05)] public byte MobHuntReward;
}
