// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct MobHuntTarget {
    [FieldOffset(0x00)] public uint Icon;
    /// <remarks>BNpcName</remarks>
    [FieldOffset(0x04)] public ushort Name;
    /// <remarks>Fate</remarks>
    [FieldOffset(0x06)] public ushort FATE;
    /// <remarks>Map</remarks>
    [FieldOffset(0x08)] public ushort TerritoryType;
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x0A)] public ushort PlaceName;
}
