// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct MobHuntOrderType {
    /// <remarks>Quest</remarks>
    [FieldOffset(0x00)] public uint Quest;
    /// <remarks>EventItem</remarks>
    [FieldOffset(0x04)] public uint EventItem;
    /// <remarks>MobHuntOrder</remarks>
    [FieldOffset(0x08)] public ushort OrderStart;
    [FieldOffset(0x0A)] public byte Type;
    [FieldOffset(0x0B)] public byte OrderAmount;
}
