// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct MotionTimelineAdvanceBlend {
    [FieldOffset(0x00)] public int Unknown0_Offset;
    [FieldOffset(0x04)] public int Unknown1_Offset;
}
