// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct MountAction {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray6<ushort> _action;
}
