// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct MovieStaffList {
    [FieldOffset(0x00)] public float StartTime;
    [FieldOffset(0x04)] public float EndTime;
    [FieldOffset(0x08)] public uint Image;
    [FieldOffset(0x0C)] public sbyte Unknown0;
}
