// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct MovieSubtitle {
    [FieldOffset(0x00)] public float StartTime;
    [FieldOffset(0x04)] public float EndTime;
}
