// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct NotoriousMonster {
    /// <remarks>BNpcName</remarks>
    [FieldOffset(0x00)] public uint BNpcName;
    /// <remarks>BNpcBase</remarks>
    [FieldOffset(0x04)] public int BNpcBase;
    [FieldOffset(0x08)] public ushort Unknown0;
    [FieldOffset(0x0A)] public byte Rank;
}
