// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x14)]
public unsafe partial struct NpcYell {
    [FieldOffset(0x00)] public int Text_Offset;
    [FieldOffset(0x04)] public float BalloonTime;
    [FieldOffset(0x08)] public uint Unknown0;
    [FieldOffset(0x0C)] public byte OutputType;
    [FieldOffset(0x0D)] public byte Unknown_70;
    [FieldOffset(0x0E)] public byte Unknown1;
    [FieldOffset(0x0F)] public byte Unknown2;
    [FieldOffset(0x10)] public BitField10Flags BitField10;
    public bool Unknown3 => BitField10.HasFlag(BitField10Flags.Unknown3);
    public bool Unknown4 => BitField10.HasFlag(BitField10Flags.Unknown4);
    public bool Unknown5 => BitField10.HasFlag(BitField10Flags.Unknown5);
    public bool IsBalloonSlow => BitField10.HasFlag(BitField10Flags.IsBalloonSlow);
    public bool BattleTalkTime => BitField10.HasFlag(BitField10Flags.BattleTalkTime);

    [Flags]
    public enum BitField10Flags : byte {
    	Unknown3 = 1 << 0,
    	Unknown4 = 1 << 1,
    	Unknown5 = 1 << 2,
    	IsBalloonSlow = 1 << 3,
    	BattleTalkTime = 1 << 4,
    }
}
