// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct OnlineStatus {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public uint Icon;
    [FieldOffset(0x08)] public int Unknown0;
    [FieldOffset(0x0C)] public byte Priority;
    [FieldOffset(0x0D)] public BitField0DFlags BitField0D;
    public bool Unknown1 => BitField0D.HasFlag(BitField0DFlags.Unknown1);
    public bool List => BitField0D.HasFlag(BitField0DFlags.List);
    public bool Unknown2 => BitField0D.HasFlag(BitField0DFlags.Unknown2);

    [Flags]
    public enum BitField0DFlags : byte {
    	Unknown1 = 1 << 0,
    	List = 1 << 1,
    	Unknown2 = 1 << 2,
    }
}
