// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x80)]
public unsafe partial struct OpenContent {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray16<OpenContentDataStruct> _openContentData;

    [StructLayout(LayoutKind.Explicit, Size = 0x08)]
    public partial struct OpenContentDataStruct {
        /// <remarks>OpenContentCandidateName</remarks>
        [FieldOffset(0x00)] public uint CandidateName;
        /// <remarks>ContentFinderCondition</remarks>
        [FieldOffset(0x04)] public ushort Content;
    }
}
