// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct Picture {
    [FieldOffset(0x00)] public int Image;
    [FieldOffset(0x04)] public int Signature;
}
