// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct PvPBaseParamValue {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public uint Unknown1;
    [FieldOffset(0x08)] public uint Unknown2;
}
