// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct PvPSelectTrait {
    [FieldOffset(0x00)] public int Effect_Offset;
    [FieldOffset(0x04)] public uint Icon;
    [FieldOffset(0x08)] public short Value;
}
