// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct PvPTrait {
    /// <remarks>Trait</remarks>
    [FieldOffset(0x00)] public ushort Trait1;
    /// <remarks>Trait</remarks>
    [FieldOffset(0x02)] public ushort Trait2;
    /// <remarks>Trait</remarks>
    [FieldOffset(0x04)] public ushort Trait3;
}
