// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct QuestSceneAbortConditionType {
    [FieldOffset(0x00)] public bool Unknown0;
    [FieldOffset(0x01)] public bool Unknown1;
}
