// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct QuestRedoChapterUITab {
    [FieldOffset(0x00)] public int Text_Offset;
    [FieldOffset(0x04)] public uint Icon1;
    [FieldOffset(0x08)] public uint Icon2;
    [FieldOffset(0x0C)] public byte Unknown0;
}
