// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x6EC)]
public unsafe partial struct QuestBattle {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray220<QuestBattleParamsStruct> _questBattleParams;
    /// <remarks>ArrayEventHandler, Quest</remarks>
    [FieldOffset(0x6E0)] public int Quest;
    [FieldOffset(0x6E4)] public ushort TimeLimit;
    [FieldOffset(0x6E6)] public ushort LevelSync;
    [FieldOffset(0x6E8)] public byte QuestBattleScene;

    [StructLayout(LayoutKind.Explicit, Size = 0x08)]
    public partial struct QuestBattleParamsStruct {
        [FieldOffset(0x00)] public int ScriptInstruction_Offset;
        [FieldOffset(0x04)] public uint ScriptValue;
    }
}
