// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct QuestEventAreaEntranceInfo {
    /// <remarks>Quest</remarks>
    [FieldOffset(0x00)] public uint Quest;
    /// <remarks>Level</remarks>
    [FieldOffset(0x04)] public uint Location;
    [FieldOffset(0x08)] public byte Unknown0;
}
