// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct QuestRedoChapterUICategory {
    [FieldOffset(0x00)] public int Expac_Offset;
    [FieldOffset(0x04)] public byte Unknown0;
}
