// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct QuestStatusParam {
    [FieldOffset(0x00)] public ushort Unknown0;
    [FieldOffset(0x02)] public short Unknown1;
    [FieldOffset(0x04)] public byte Unknown2;
}
