// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct QuestLinkMarkerSet {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public ushort Unknown1;
    [FieldOffset(0x06)] public byte Unknown2;
    [FieldOffset(0x07)] public byte Unknown3;
    [FieldOffset(0x08)] public byte Unknown4;
    [FieldOffset(0x09)] public BitField09Flags BitField09;
    public bool Unknown5 => BitField09.HasFlag(BitField09Flags.Unknown5);
    public bool Unknown6 => BitField09.HasFlag(BitField09Flags.Unknown6);

    [Flags]
    public enum BitField09Flags : byte {
    	Unknown5 = 1 << 0,
    	Unknown6 = 1 << 1,
    }
}
