// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct QuickChat {
    [FieldOffset(0x00)] public int NameAction_Offset;
    [FieldOffset(0x04)] public int Icon;
    /// <remarks>Addon</remarks>
    [FieldOffset(0x08)] public int Addon;
    [FieldOffset(0x0C)] public ushort Unknown0;
    /// <remarks>QuickChatTransient</remarks>
    [FieldOffset(0x0E)] public sbyte QuickChatTransient;
}
