// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct RacingChocoboItem {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public int Item;
    [FieldOffset(0x04)] public byte Category;
    [FieldOffset(0x05)] public byte Unknown0;
    [FieldOffset(0x06)] public byte Unknown1;
}
