// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct RecipeLookup {
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x00)] public ushort CRP;
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x02)] public ushort BSM;
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x04)] public ushort ARM;
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x06)] public ushort GSM;
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x08)] public ushort LTW;
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x0A)] public ushort WVR;
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x0C)] public ushort ALC;
    /// <remarks>Recipe</remarks>
    [FieldOffset(0x0E)] public ushort CUL;
}
