// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct RecipeSubCategory {
    [FieldOffset(0x00)] public int Unknown0_Offset;
    [FieldOffset(0x04)] public byte Unknown1;
}
