// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x3C)]
public unsafe partial struct RelicNote {
    /// <remarks>EventItem</remarks>
    [FieldOffset(0x00)] public uint EventItem;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray10<ushort> _monsterNoteTargetCommon;
    [FieldOffset(0x18), FixedSizeArray] internal FixedSizeArray3<ushort> _monsterNoteTargetNM;
    [FieldOffset(0x1E)] public ushort Unknown0;
    [FieldOffset(0x20), FixedSizeArray] internal FixedSizeArray3<ushort> _fate;
    [FieldOffset(0x26), FixedSizeArray] internal FixedSizeArray3<ushort> _placeNameFate;
    [FieldOffset(0x2C), FixedSizeArray] internal FixedSizeArray3<ushort> _leve;
    [FieldOffset(0x32), FixedSizeArray] internal FixedSizeArray10<byte> _monsterCount;
}
