// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct RelicNoteCategory {
    [FieldOffset(0x00)] public int Text_Offset;
    [FieldOffset(0x04)] public sbyte Unknown0;
}
