// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct Relic3RatePattern {
    [FieldOffset(0x00)] public sbyte Unknown0;
    [FieldOffset(0x01)] public sbyte Unknown1;
    [FieldOffset(0x02)] public sbyte Unknown2;
}
