// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct RideShootingTarget {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public uint Unknown1;
    [FieldOffset(0x08)] public uint Unknown2;
    [FieldOffset(0x0C)] public byte Unknown3;
    [FieldOffset(0x0D)] public byte Unknown4;
    [FieldOffset(0x0E)] public byte Unknown5;
}
