// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct SatisfactionArbitration {
    /// <remarks>Quest</remarks>
    [FieldOffset(0x00)] public uint Quest;
    [FieldOffset(0x04)] public byte SatisfactionLevel;
    /// <remarks>SatisfactionNpc</remarks>
    [FieldOffset(0x05)] public byte SatisfactionNpc;
    [FieldOffset(0x06)] public byte Unknown0;
}
