// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct SecretRecipeBook {
    [FieldOffset(0x00)] public int Name_Offset;
    /// <remarks>Item</remarks>
    [FieldOffset(0x04)] public int Item;
}
