// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct SnipeCollision {
    [FieldOffset(0x00)] public ushort Unknown0;
    [FieldOffset(0x02)] public ushort Unknown1;
    [FieldOffset(0x04)] public ushort Unknown2;
    [FieldOffset(0x06)] public byte Unknown3;
    [FieldOffset(0x07)] public byte Unknown4;
}
