// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct SnipeTalk {
    [FieldOffset(0x00)] public int Text_Offset;
    [FieldOffset(0x04)] public int Unknown0_Offset;
    [FieldOffset(0x08)] public int Unknown1_Offset;
    /// <remarks>SnipeTalkName</remarks>
    [FieldOffset(0x0C)] public ushort Name;
    [FieldOffset(0x0E)] public byte Unknown2;
    [FieldOffset(0x0F)] public byte Unknown3;
}
