// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct Stain {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public int Name2_Offset;
    [FieldOffset(0x08)] public uint Color;
    [FieldOffset(0x0C)] public byte Shade;
    [FieldOffset(0x0D)] public byte SubOrder;
    [FieldOffset(0x0E)] public BitField0EFlags BitField0E;
    public bool Unknown1 => BitField0E.HasFlag(BitField0EFlags.Unknown1);
    public bool Unknown2 => BitField0E.HasFlag(BitField0EFlags.Unknown2);

    [Flags]
    public enum BitField0EFlags : byte {
    	Unknown1 = 1 << 0,
    	Unknown2 = 1 << 1,
    }
}
