// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x0C)]
public unsafe partial struct TofuPresetObject {
    [FieldOffset(0x00)] public int Unknown0;
    [FieldOffset(0x04)] public ushort Unknown1;
    [FieldOffset(0x06)] public ushort Unknown2;
    [FieldOffset(0x08)] public short Unknown3;
    [FieldOffset(0x0A)] public byte Unknown4;
    [FieldOffset(0x0B)] public BitField0BFlags BitField0B;
    public bool Unknown5 => BitField0B.HasFlag(BitField0BFlags.Unknown5);
    public bool Unknown6 => BitField0B.HasFlag(BitField0BFlags.Unknown6);

    [Flags]
    public enum BitField0BFlags : byte {
    	Unknown5 = 1 << 0,
    	Unknown6 = 1 << 1,
    }
}
