// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct TomestoneConvert {
    [FieldOffset(0x00)] public int Unknown0_Offset;
    [FieldOffset(0x04)] public byte Unknown1;
    [FieldOffset(0x05)] public byte Unknown2;
    [FieldOffset(0x06)] public byte Unknown3;
    [FieldOffset(0x07)] public bool Unknown4;
}
