// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x30)]
public unsafe partial struct TopicSelect {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray10<uint> _shop;
    [FieldOffset(0x2C)] public ushort Unknown0;
    [FieldOffset(0x2E)] public byte Unknown1;
    [FieldOffset(0x2F)] public bool Unknown2;
}
