// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct VaseFlower {
    /// <remarks>Item</remarks>
    [FieldOffset(0x00)] public uint Item;
    [FieldOffset(0x04)] public ushort Unknown0;
    [FieldOffset(0x06)] public byte Unknown1;
    [FieldOffset(0x07)] public byte Unknown2;
}
