// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x34)]
public unsafe partial struct VVDNotebookSeries {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04), FixedSizeArray] internal FixedSizeArray12<int> _contents;
}
