// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x68)]
public unsafe partial struct WarpLogic {
    [FieldOffset(0x00), FixedSizeArray] internal FixedSizeArray10<WarpParamsStruct> _warpParams;
    [FieldOffset(0x50)] public int Question_Offset;
    [FieldOffset(0x54)] public int ResponseYes_Offset;
    [FieldOffset(0x58)] public int ResponseNo_Offset;
    [FieldOffset(0x5C)] public int WarpName_Offset;
    [FieldOffset(0x60)] public uint Unknown0;
    [FieldOffset(0x64)] public bool CanSkipCutscene;

    [StructLayout(LayoutKind.Explicit, Size = 0x08)]
    public partial struct WarpParamsStruct {
        [FieldOffset(0x00)] public int Function_Offset;
        /// <remarks>HowTo, Item, Quest</remarks>
        [FieldOffset(0x04)] public uint Argument;
    }
}
