// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x04)]
public unsafe partial struct WeatherReportReplace {
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x00)] public ushort PlaceNameSub;
    /// <remarks>PlaceName</remarks>
    [FieldOffset(0x02)] public ushort PlaceNameParent;
}
