// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x1C)]
public unsafe partial struct Weather {
    [FieldOffset(0x00)] public int Name_Offset;
    [FieldOffset(0x04)] public int Description_Offset;
    [FieldOffset(0x08)] public int Unknown0_Offset;
    [FieldOffset(0x0C)] public int Unknown1_Offset;
    [FieldOffset(0x10)] public int Unknown2_Offset;
    [FieldOffset(0x14)] public int Unknown3_Offset;
    [FieldOffset(0x18)] public int Icon;
}
