// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x18)]
public unsafe partial struct YKW {
    [FieldOffset(0x00)] public int Unknown0_Offset;
    /// <remarks>Item</remarks>
    [FieldOffset(0x04)] public uint Item;
    [FieldOffset(0x08)] public ushort Unknown1;
    [FieldOffset(0x0A), FixedSizeArray] internal FixedSizeArray6<ushort> _location;
}
