// <auto-generated/>
namespace FFXIVClientStructs.FFXIV.Component.Excel.Sheets;

[StructLayout(LayoutKind.Explicit, Size = 0x08)]
public unsafe partial struct ZoneTimeline {
    [FieldOffset(0x00)] public uint Unknown0;
    [FieldOffset(0x04)] public byte Unknown1;
    [FieldOffset(0x05)] public byte Unknown2;
    [FieldOffset(0x06)] public byte Unknown3;
}
