namespace FFXIVClientStructs.FFXIV.Client.UI.Agent;

// Client::UI::Agent::AgentModule
[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0xF80)]
public unsafe partial struct AgentModule {
    public static AgentModule* Instance() {
        var uiModule = UI.UIModule.Instance();
        return uiModule == null ? null : uiModule->GetAgentModule();
    }

    [FieldOffset(0x8)] public UIModule* UIModule;
    [FieldOffset(0x10)] public byte Initialized;
    [FieldOffset(0x14)] public uint FrameCounter;
    [FieldOffset(0x18)] public float FrameDelta;

    [FieldOffset(0x20), FixedSizeArray] internal FixedSizeArray490<Pointer<AgentInterface>> _agents;
    [FieldOffset(0xF70)] public AgentHelpers AgentHelpers;

    [MemberFunction("E8 ?? ?? ?? ?? 83 7B 48 00")]
    public partial AgentInterface* GetAgentByInternalId(AgentId agentId);
}

[GenerateInterop]
[StructLayout(LayoutKind.Explicit, Size = 0x10)]
public unsafe partial struct AgentHelpers {
    [FieldOffset(0x0)] public UIModule* UIModule;
    [FieldOffset(0x8)] public AgentModule* AgentModule;

    [MemberFunction("E8 ?? ?? ?? ?? 0F 10 45 ?? 48 8D 0D")]
    public partial void HideBlockingCharaViewAgents(uint clientObjectIndex, AgentId allowedAgent);
}

public enum AgentId : uint {
    Lobby = 0,
    CharaMake = 1,
    MovieStaffList = 2, // this is the addon name, no idea what the agent actually is, shows up when playing the EW cutscene in title
    Cursor = 3,
    Hud = 4,
    ChatLog = 5,
    Inventory = 6,
    ScenarioTree = 7,
    EventFade = 8,
    Context = 9,
    InventoryContext = 10,
    GlassesContext = 11,
    Config = 12, // ConfigSystem
    ConfigLog = 13,
    ConfigLogColor = 14,
    Configkey = 15,
    ConfigCharacter = 16,
    ConfigPadcustomize = 17,
    ChatConfig = 18,
    ChatLogNameConfig = 19,
    HudLayout = 20,
    Emote = 21,
    Macro = 22,
    TargetCircle = 23, // TargetCursor
    GatheringNote = 24,
    RecipeNote = 25,
    RecipeTree = 26,
    RecipeMaterialList = 27,
    RecipeProductList = 28,
    FishingNote = 29,
    FishGuide = 30,
    FishRecord = 31,
    FishRelease = 32,
    QuestJournal = 33,
    ActionMenu = 34,
    Marker = 35,
    Trade = 36,
    ScreenLog = 37,
    NpcTrade = 38,
    Status = 39,
    Map = 40,
    Loot = 41, // NeedGreed
    Repair = 42,
    RepairRequest = 43,
    Materialize = 44,
    MateriaAttach = 45,
    MiragePrism = 46,
    Colorant = 47,
    Howto = 48,
    HowtoNotice = 49,
    ContentsTutorial = 50,
    Inspect = 51,
    Teleport = 52,
    TelepotTown = 53, // Aethernet
    ContentsFinder = 54,
    ContentsFinderSetting = 55,
    Social = 56,
    Blacklist = 57,
    Mutelist = 58,
    Friendlist = 59,
    Linkshell = 60,
    PartyMember = 61,
    PartyInvite = 62,
    Search = 63,
    Detail = 64,
    LetterList = 65,
    LetterView = 66,
    LetterEdit = 67,
    ItemDetail = 68,
    ActionDetail = 69,
    Retainer = 70,
    Return = 71,
    Cutscene = 72,
    CutsceneReplay = 73,
    MonsterNote = 74,
    ItemSearch = 75, // MarketBoard
    GoldSaucerReward = 76,
    FateProgress = 77, // Shared FATE
    Catch = 78,
    FreeCompany = 79,
    FreeCompanyOrganizeSheet = 80,
    FreeCompanyProfile = 81,
    FreeCompanyProfileEdit = 82,
    FreeCompanyInvite = 83,
    FreeCompanyInputString = 84,
    FreeCompanyChest = 85,
    FreeCompanyExchange = 86,
    FreeCompanyCrestEditor = 87,
    FreeCompanyCrestDecal = 88,
    FreeCompanyPetition = 89,
    ArmouryBoard = 90,
    HowtoList = 91,
    Cabinet = 92,
    CabinetWithdraw = 93,
    LegacyItemStorage = 94,
    GrandCompanyRank = 95,
    GrandCompanySupply = 96,
    GrandCompanyExchange = 97,
    GearSet = 98,
    SupportMain = 99,
    SupportList = 100,
    SupportView = 101,
    SupportEdit = 102,
    Achievement = 103,
    CrossEditor = 104,
    LicenseViewer = 105,
    ContentsTimer = 106,
    MovieSubtitle = 107,
    PadMouseMode = 108,
    RecommendList = 109,
    Buddy = 110,
    ColosseumRecord = 111, // PVP Results
    CloseMessage = 112,
    CreditPlayer = 113,
    CreditScroll = 114,
    CreditCast = 115,
    CreditEnd = 116,
    CreditCutCast = 117,
    Shop = 118,
    Bait = 119,
    Housing = 120,
    HousingHarvest = 121,
    HousingSignboard = 122,
    HousingPortal = 123,
    HousingTravellersNote = 124,
    HousingPlant = 125,
    PersonalRoomPortal = 126,
    HousingBuddyList = 127,
    TreasureHunt = 128,
    Salvage = 129,
    LookingForGroup = 130,
    ContentsMvp = 131,
    VoteKick = 132,
    VoteGiveUp = 133,
    VoteTreasure = 134,
    PvpProfile = 135,
    ContentsNote = 136,
    ReadyCheck = 137,
    FieldMarker = 138,
    CursorLocation = 139,
    CursorRect = 140,
    RetainerStatus = 141,
    RetainerTask = 142,
    RetainerTaskSupply = 143,
    Unk144 = 144,
    RetainerItemTransfer = 145,
    RelicGlass = 146,
    RelicNotebook = 147,
    RelicSphere = 148,
    TradeMultiple = 149,
    RelicSphereUpgrade = 150,
    AWGrowthFragTrade = 151, // AnimaWeapon5TradeItem
    AWMakingSpiritGrow = 152, // AnimaWeapon5SpiritTalk
    Relic2Glass = 153,
    Minigame = 154,
    Tryon = 155,
    TryonRetainer = 156,
    AdventureNotebook = 157,
    ArmouryNotebook = 158,
    MinionNotebook = 159,
    MountNotebook = 160,
    ItemComp = 161,
    DailyQuestSupply = 162,
    MobHunt = 163,
    PatchMark = 164, // SelectOk?
    HousingWithdrawStorage = 165,
    WeatherReport = 166,
    Wedding = 167,
    LoadingTips = 168,
    Revive = 169,
    Unk170 = 170, // something with RaceChocobo director/todo
    ChocoboRace = 171,
    ChocoboBreed = 172,
    GoldSaucerMiniGame = 173,
    TrippleTriad = 174,
    TripleTriadRuleAnnounce = 175,
    TripleTriadRuleSetting = 176,
    Unk177 = 177,
    TripleTriadSchedule = 178,
    TripleTriadRanking = 179,
    TripleTriadTournamentResult = 180,
    TripleTriadTournamentMatchList = 181,
    LotteryDaily = 182,
    AetherialWheel = 183,
    LotteryWeekly = 184,
    GoldSaucer = 185,
    TripleTriadCoinExchange = 186,
    ShopExchangeCoin = 187, // MGP Exchange
    JournalAccept = 188,
    JournalResult = 189,
    LeveQuest = 190,
    CompanyCraftRecipeNoteBook = 191,
    AirShipParts = 192,
    AirShipExploration = 193,
    AirShipExplorationResult = 194,
    AirShipExplorationDetail = 195,
    SubmersibleParts = 196,
    SubmersibleExploration = 197,
    SubmersibleExplorationResult = 198,
    SubmersibleExplorationDetail = 199,
    CompanyCraftMaterial = 200,
    AetherCurrent = 201,
    FreeCompanyCreditShop = 202,
    Currency = 203,
    Purify = 204, // Aetherial Reduction
    SkyIslandExchange = 205,
    LovmParty = 206,
    LovmRanking = 207,
    LovmNamePlate = 208,
    CharacterTitle = 209,
    CharacterTitleSelect = 210,
    LovmResult = 211,
    LovmPaletteEdit = 212,
    SkyIslandFinder = 213, // Exploratory Missions
    SkyIslandFinderSetting = 214,
    SkyIslandResult = 215,
    SkyIsland2Result = 216,
    ItemContextCustomize = 217,
    BeginnersMansionProblem = 218, // Hall of the Novice
    DpsChallenge = 219, // Stone, Sky, Sea
    PlayGuide = 220,
    WebLauncher = 221,
    WebGuidance = 222,
    Orchestrion = 223,
    BeginnerChatList = 224, // Novice Network
    Unk225 = 225, // BeginnerChatKick?
    BeginnerChatInvite = 226,
    ReturnerDialog = 227,
    OrchestrionInn = 228,
    HousingEditContainer = 229,
    ConfigPartyListRoleSort = 230,
    RecommendEquip = 231,
    YkwNote = 232, // Yo-kai Watch Medallium
    ContentsFinderMenu = 233,
    RaidFinder = 234,
    GcArmyExpedition = 235,
    GcArmyMemberList = 236,
    Unk237 = 237,
    DeepDungeonInspect = 238,
    DeepDungeonMap = 239,
    DeepDungeonStatus = 240,
    DeepDungeonSaveData = 241,
    DeepDungeonScore = 242,
    DeepDungeonHard = 243,
    GcArmyTraining = 244,
    GcArmyMenberProfile = 245,
    GcArmyExpeditionResult = 246,
    GcArmyCapture = 247,
    GcArmyOrder = 248,
    MansionSelectRoom = 249,
    OrchestrionPlayList = 250,
    CountDownSettingDialog = 251,
    WeeklyBingo = 252, // Wondrous Tails
    WeeklyPuzzle = 253, // Faux Hollows
    CameraSetting = 254,
    PvPDuelRequest = 255,
    PvPHeader = 256,
    PvPGauge = 257, // PvPFrontlineGauge
    PvPSpectator = 258, // PvPMKSHeaderSpec, PvPSpectatorCameraList, PvPSpectatorList
    Unk259 = 259,
    Aquarium = 260,
    QTE = 261,
    DeepDungeonMenu = 262,
    ContextIconMenu = 263,
    DeepDungeonResult = 264,
    ItemAppraisal = 265, // DeepDungeon Appraisal
    ItemInspection = 266, // Lockbox
    RecipeItemContext = 267, // context menus for RecipeTree and RecipeList, constructor inlined
    ContactList = 268,
    PicturePreview = 269, // Preview for Sightseeing Log, Landscapes, Portraits
    McAggre = 270,
    SatisfactionSupply = 271,
    SatisfactionSupplyResult = 272,
    SatisfactionList = 273,
    Snipe = 274,
    MountSpeed = 275,
    PvpScreenInformationHotBar = 276,
    PvpWelcome = 277,
    JobHudNotice = 278,
    TreasureHighLow = 279, // Gambler's Lure
    ManeuversArmorBoarding = 280, // Rival Wings
    ManeuversHud = 281, // Rival Wings
    UserPolicyPerformance = 282,
    PvpTeam = 283,
    PvpTeamInputString = 284,
    PvpTeamMember = 285,
    PvPTeamResult = 286,
    Unk287 = 287,
    Unk288 = 288,
    PvpTeamCrestEditor = 289,
    PvPTeamOrganization = 290,
    Unk291 = 291,
    EurekaElementalHud = 292,
    EurekaElementalEdit = 293,
    EurekaChainInfo = 294,
    Unk295 = 295, // EurekaLogos?
    EurekaMagiaActionNotebook = 296, // unconfirmed
    EurekaWeaponAdjust = 297,
    TeleportHousingFriend = 298,
    ContentMemberList = 299,
    InventoryBuddy = 300,
    ContentsReplayPlayer = 301,
    ContentsReplaySetting = 302,
    MiragePrismPrismBox = 303, // Glamour Dresser
    MiragePrismPrismItemDetail = 304,
    MiragePrismPrismSetConvert = 305,
    MiragePrismMiragePlate = 306, // Glamour Plates
    PerformanceMode = 307,
    PerformanceModeSettings = 308,
    RecordReadyCheck = 309,
    Fashion = 310,
    Unk311 = 311, // PvPTeamOrganization again?
    SelectYesno = 312,
    HousingGuestBook = 313,
    Unk314 = 314, // GridMenu? SelectCustomString?
    Unk315 = 315, // SelectStringEventGimmick? for some QuestEventHandler
    ReconstructionBox = 316,
    ReconstructionBuyback = 317,
    CrossWorldLinkShell = 318,
    MiragePrismENpcSatisfaction = 319,
    Description = 320, // Frontline/Bozja Description
    Alarm = 321,
    Unk322 = 322,
    MerchantSetting = 323, // Mannequins
    FreeShop = 324,
    AozNotebook = 325, // Bluemage Spells
    RhythmAction = 326,
    WeddingNotification = 327,
    Emj = 328, // Mahjong
    Unk329 = 329,
    Unk330 = 330,
    EmjIntro = 331,
    EmjVoiceCharacter = 332,
    AozContentBriefing = 333, // Masked Carnivale
    AozContentResult = 334,
    WorldTravel = 335,
    RideShooting = 336, // Airforce One
    RideShootingResult = 337,
    Credit = 338,
    EmjSetting = 339, // Mahjong Settings
    RetainerList = 340,
    QIBCStatus = 341,
    HugeCraftworksSupply = 342, // Crystarium Deliveries
    HugeCraftworksSupplyResult = 343,
    SharlayanCraftworksSupply = 344, // Studium Deliveries
    BankaCraftworksSupply = 345, // Wachumeqimeqi Deliveries
    Dawn = 346, // Trust
    DawnStory = 347, // Duty Support
    HousingCatalogPreview = 348,
    Unk349 = 349,
    SubmersibleExplorationMapSelect = 350,
    QuestRedo = 351,
    QuestRedoHud = 352,
    CircleInvite = 353, // Fellowships
    CircleList = 354,
    CircleBook = 355,
    CircleBookSetting = 356,
    CircleBookBlackList = 357,
    CircleBookQuestion = 358,
    CircleBookGroupSetting = 359,
    CircleFinder = 360,
    CircleFinderSetting = 361,
    MentorCondition = 362,
    PerformanceMetronome = 363,
    PerformanceGamepadGuide = 364,
    PerformancePlayGuide = 365,
    PerformanceReadyCheck = 366,
    HwdInfoBoard = 367,
    HwdLottery = 368,
    HwdSupply = 369,
    HwdAetherGauge = 370,
    HwdGathererInspection = 371,
    HwdScore = 372,
    HwdGathererInspectionItemCount = 373,
    HwdMonument = 374,
    McGuffin = 375, // Collection
    CraftActionSimulator = 376,
    IKDSchedule = 377, // Ocean Fishing
    IKDFishingLog = 378,
    IKDResult = 379,
    IKDMission = 380,
    InclusionShop = 381, // Item Exchange
    CollectablesShop = 382,
    MycWarResultNotebook = 383,
    MycInfo = 384, // Bozja Info
    MycItemBox = 385, // Bozja Lost Finds Cache
    MycItemBag = 386, // Bozja Lost Finds Holster
    MycDuelRequest = 387,
    MycBattleAreaInfo = 388, // Bozja Recruitment
    MycWeaponAdjust = 389,
    OrnamentNoteBook = 390, // Accessories
    TalkSubtitle = 391,
    TourismMenu = 392,
    GatheringMasterpiece = 393,
    StarlightGiftBox = 394,
    HalloweenNpcSelect = 395,
    Unk396 = 396, // new in 7.4
    SpearFishing = 397,
    Omikuji = 398,
    FittingShop = 399,
    AkatsukiNote = 400, // Unending Codex
    ExHotbarEditor = 401,
    BannerList = 402, // Portraits
    BannerEditor = 403, // Portrait Editor
    BannerUpdateView = 404,
    BannerPreview = 405,
    Unk406 = 406,
    PvPMap = 407,
    CharaCard = 408, // AdventurerPlate
    CharaCardDesignSetting = 409,
    CharaCardProfileSetting = 410,
    PvPMKSRankRating = 411,
    PvPMKSIntroduction = 412,
    MJIHud = 413, // Island Sanctuary
    MJIPouch = 414,
    MJIRecipeNoteBook = 415,
    MJICraftSchedule = 416,
    MJICraftSales = 417,
    MJIAnimalManagement = 418,
    MJIFarmManagement = 419,
    MJIGatheringHouse = 420,
    MJIBuilding = 421,
    MJIGatheringNoteBook = 422,
    MJIDisposeShop = 423,
    MJIMinionManagement = 424,
    MJIMinionNoteBook = 425,
    MJIBuildingMove = 426,
    MJIEntrance = 427,
    MJISettings = 428,
    MJIHousingMenu = 429,
    MJINekomimiRequest = 430, // favors
    Unk431 = 431,
    ArchiveItem = 432,
    Class2JobHotbar = 433,
    VVDNotebook = 434,
    VVDFinder = 435,
    Unk436 = 436, // 7.4
    TofuList = 437,
    TofuPreview = 438,
    TofuEdit = 439,
    TofuImport = 440,
    TofuExport = 441,
    BannerParty = 442,
    BannerMIP = 443,
    TurnBreak = 444,
    MandervilleWeapon = 445,
    SXTBattleLog = 446,
    MoogleCollection = 447,
    FGSEnterDialog = 448,
    FGSStageIntro = 449,
    FGSHud = 450,
    FGSWinner = 451,
    FGSResult = 452,
    PointMenu = 453,
    TradeScreenImage = 454,
    Glasses = 455,
    TermFilter = 456,
    HousingInteriorPattern = 457,
    WKSHud = 458,
    WKSAnnounce = 459,
    WKSPouch = 460,
    WKSMission = 461,
    WKSMissionInfomation = 462,
    WKSRecipeNotebook = 463,
    WKSMechaOperationEntry = 464,
    WKSScoreList = 465,
    WKSAchievement = 466,
    WKSPraiseBoard = 467,
    WKSLottery = 468,
    WKSToolCustomize = 469,
    WKSHistoryBoard = 470,
    WKSPlanetSelect = 471,
    WKSSetting = 472,
    WKSEnterInfo = 473,
    MKDInfo = 474,
    MKDContentsInfo = 475,
    MKDSupportJob = 476,
    MKDSupportJobList = 477,
    MKDSettings = 478,
    MKDTowerEntry = 479,
    Unk480 = 480, // new in 7.2 - interacts with agents MKDLoreBook, MKDInfo
    MKDLoreBook = 481,
    MKDRelicGrowth = 482,
    MKDRelicGrowth2 = 483,
    QuickPanel = 484,
    Unk485 = 485, // new in 7.4
    ConfigCharacterChatLogMiniTalk = 486,
    ToggleContextMenu = 487,
    Unk488 = 488, // new in 7.3
    Unk489 = 489, // new in 7.4
}
