using Xunit;
using VerifyIG = FFXIVClientStructs.InteropGenerator.Tests.Helpers.IncrementalGeneratorVerifier<FFXIVClientStructs.InteropGenerator.Generator.InteropGenerator>;

namespace FFXIVClientStructs.InteropGenerator.Tests;

public class GeneralTests {
    [Fact]
    public async Task NoMarkerAttribute() {
        var code = """
                   using FFXIVClientStructs.InteropGenerator.Runtime.Attributes;

                   public partial struct TestStruct
                   {
                   }
                   """;

        await VerifyIG.VerifyGeneratorAsync(
            code,
            []);
    }
    
    [Fact]
    public async Task MarkerAttribute() {
        var code = """
                   using FFXIVClientStructs.InteropGenerator.Runtime.Attributes;                
                   
                   [GenerateInterop]
                   public partial struct TestStruct
                   {
                   }
                   """;

        var result = """
                     // <auto-generated/>
                     unsafe partial struct TestStruct
                     {
                     }
                     """;

        await VerifyIG.VerifyGeneratorAsync(
            code,
            ("TestStruct.InteropGenerator.g.cs", result));
    }
    
    [Fact]
    public async Task Namespace() {
        var code = """
                   using FFXIVClientStructs.InteropGenerator.Runtime.Attributes;

                   namespace TestNamespace.InnerNamespace;
                   
                   [GenerateInterop]
                   public partial struct TestStruct
                   {
                   }
                   """;

        var result = """
                     // <auto-generated/>
                     namespace TestNamespace.InnerNamespace;
                     
                     unsafe partial struct TestStruct
                     {
                     }
                     """;

        await VerifyIG.VerifyGeneratorAsync(
            code,
            ("TestNamespace.InnerNamespace.TestStruct.InteropGenerator.g.cs", result));
    }
}
