using Xunit;
using VerifyIG = InteropGenerator.Tests.Helpers.IncrementalGeneratorVerifier<InteropGenerator.Generator.InteropGenerator>;

namespace InteropGenerator.Tests.Generator;

public partial class BitFieldAttributeTests {
    [Fact]
    public async Task GenerateBitField() {
        const string code = """
                            [GenerateInterop]
                            public partial struct TestStruct
                            {
                                [BitField<bool>(nameof(TestBool1), 0)]
                                [BitField<bool>(nameof(TestBool2), 1)]
                                [BitField<TestEnum>(nameof(TestEnum1), 2, 2)]
                                internal byte _testField1;
                            
                                [BitField<bool>(nameof(TestBool3), 0)]
                                [BitField<ushort>(nameof(TestShort1), 2, 16)]
                                [BitField<ushort>(nameof(TestShort2), 18, 4)]
                                [BitField<TestEnum>(nameof(TestEnum2), 24, 2)]
                                internal uint _testField2;

                                [Flags]
                                public enum TestEnum {
                                    TestValue1 = 1 << 0,
                                    TestValue2 = 1 << 1,
                                }
                            }
                            """;

        const string result = """
                              // <auto-generated/>
                              unsafe partial struct TestStruct
                              {
                                  public bool TestBool1
                                  {
                                      get => BitOps.GetBit<byte>(_testField1, 0);
                                      set => _testField1 = BitOps.SetBit<byte>(_testField1, 0, value);
                                  }
                                  public bool TestBool2
                                  {
                                      get => BitOps.GetBit<byte>(_testField1, 1);
                                      set => _testField1 = BitOps.SetBit<byte>(_testField1, 1, value);
                                  }
                                  public global::TestStruct.TestEnum TestEnum1
                                  {
                                      get => (global::TestStruct.TestEnum)BitOps.GetBits<byte>(_testField1, 2, BitOps.CreateLowBitMask<byte>(2));
                                      set => _testField1 = BitOps.SetBits<byte>(_testField1, 2, BitOps.CreateLowBitMask<byte>(2), (byte)value);
                                  }
                                  public bool TestBool3
                                  {
                                      get => BitOps.GetBit<uint>(_testField2, 0);
                                      set => _testField2 = BitOps.SetBit<uint>(_testField2, 0, value);
                                  }
                                  public ushort TestShort1
                                  {
                                      get => (ushort)BitOps.GetBits<uint>(_testField2, 2, BitOps.CreateLowBitMask<uint>(16));
                                      set => _testField2 = BitOps.SetBits<uint>(_testField2, 2, BitOps.CreateLowBitMask<uint>(16), (uint)value);
                                  }
                                  public ushort TestShort2
                                  {
                                      get => (ushort)BitOps.GetBits<uint>(_testField2, 18, BitOps.CreateLowBitMask<uint>(4));
                                      set => _testField2 = BitOps.SetBits<uint>(_testField2, 18, BitOps.CreateLowBitMask<uint>(4), (uint)value);
                                  }
                                  public global::TestStruct.TestEnum TestEnum2
                                  {
                                      get => (global::TestStruct.TestEnum)BitOps.GetBits<uint>(_testField2, 24, BitOps.CreateLowBitMask<uint>(2));
                                      set => _testField2 = BitOps.SetBits<uint>(_testField2, 24, BitOps.CreateLowBitMask<uint>(2), (uint)value);
                                  }
                              }
                              """;

        await VerifyIG.VerifyGeneratorAsync(
            code,
            ("TestStruct.InteropGenerator.g.cs", result));
    }

    [Fact]
    public async Task GenerateBitFieldWithDefinition() {
        const string code = """
                            [GenerateInterop]
                            public partial struct TestStruct
                            {
                                [BitField<bool>(nameof(TestBool1), 0)]
                                [BitField<bool>(nameof(TestBool2), 1)]
                                [BitField<TestEnum>(nameof(TestEnum1), 2, 2)]
                                internal byte _testField1;
                            
                                [BitField<bool>(nameof(TestBool3), 0)]
                                [BitField<ushort>(nameof(TestShort1), 2, 16)]
                                [BitField<ushort>(nameof(TestShort2), 18, 4)]
                                [BitField<TestEnum>(nameof(TestEnum2), 24, 2)]
                                internal uint _testField2;
                            
                                [Flags]
                                public enum TestEnum {
                                    TestValue1 = 1 << 0,
                                    TestValue2 = 1 << 1,
                                }

                                public partial bool TestBool1 { get; set; }
                            
                                public partial bool TestBool2 { get; }
                            
                                public partial TestEnum TestEnum1 { get; set; }
                            
                                public partial bool TestBool3 { get; set; }
                            
                                public partial ushort TestShort1 { get; set; }

                                public partial ushort TestShort2 { get; }
                            
                                public partial TestEnum TestEnum2 { get; }
                            }
                            """;

        const string result = """
                              // <auto-generated/>
                              unsafe partial struct TestStruct
                              {
                                  public partial bool TestBool1
                                  {
                                      get => BitOps.GetBit<byte>(_testField1, 0);
                                      set => _testField1 = BitOps.SetBit<byte>(_testField1, 0, value);
                                  }
                                  public partial bool TestBool2
                                  {
                                      get => BitOps.GetBit<byte>(_testField1, 1);
                                  }
                                  public partial global::TestStruct.TestEnum TestEnum1
                                  {
                                      get => (global::TestStruct.TestEnum)BitOps.GetBits<byte>(_testField1, 2, BitOps.CreateLowBitMask<byte>(2));
                                      set => _testField1 = BitOps.SetBits<byte>(_testField1, 2, BitOps.CreateLowBitMask<byte>(2), (byte)value);
                                  }
                                  public partial bool TestBool3
                                  {
                                      get => BitOps.GetBit<uint>(_testField2, 0);
                                      set => _testField2 = BitOps.SetBit<uint>(_testField2, 0, value);
                                  }
                                  public partial ushort TestShort1
                                  {
                                      get => (ushort)BitOps.GetBits<uint>(_testField2, 2, BitOps.CreateLowBitMask<uint>(16));
                                      set => _testField2 = BitOps.SetBits<uint>(_testField2, 2, BitOps.CreateLowBitMask<uint>(16), (uint)value);
                                  }
                                  public partial ushort TestShort2
                                  {
                                      get => (ushort)BitOps.GetBits<uint>(_testField2, 18, BitOps.CreateLowBitMask<uint>(4));
                                  }
                                  public partial global::TestStruct.TestEnum TestEnum2
                                  {
                                      get => (global::TestStruct.TestEnum)BitOps.GetBits<uint>(_testField2, 24, BitOps.CreateLowBitMask<uint>(2));
                                  }
                              }
                              """;

        await VerifyIG.VerifyGeneratorAsync(
            code,
            ("TestStruct.InteropGenerator.g.cs", result));
    }
}
