namespace InteropGenerator.Tests.Helpers;

public static class GlobalUsings {
    public const string GetSource = """
                              // <auto-generated/>
                              global using global::System;
                              global using global::System.Collections.Generic;
                              global using global::System.IO;
                              global using global::System.Linq;
                              global using global::System.Net.Http;
                              global using global::System.Threading;
                              global using global::System.Threading.Tasks;
                              
                              global using global::System.Runtime.InteropServices;
                              global using global::System.Runtime.CompilerServices;

                              global using InteropGenerator.Runtime;
                              global using InteropGenerator.Runtime.Attributes;
                              """;
}
