// <auto-generated/>
namespace FFXIVClientStructs.GeneratedAttributes;

[AttributeUsage(AttributeTargets.Method)]
public class VirtualFunctionAttribute : Attribute
{
    public VirtualFunctionAttribute(uint index)
    {
        this.Index = index;
    }

    public uint Index { get; }
}